services:
  postgres:
    image: postgres:16
    container_name: tentotalenglish-postgres
    environment:
      POSTGRES_USER: tentotalenglish
      POSTGRES_PASSWORD: tentotalenglish
      POSTGRES_DB: tentotalenglish_db
    ports:
      - "5432:5432"
    volumes:
      - tentotalenglish_pgdata:/var/lib/postgresql/data

volumes:
  tentotalenglish_pgdata:
